table mv_produtos_com_estoque_sem_vendas_mais_de_90_dias
	lineageTag: 0bbcb54f-5c27-44ca-ab36-d08b08377109

	measure *vlr_total_vendido =
			CALCULATE(SUM(mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[vlr_total_vendido]),
			    USERELATIONSHIP(produto_gcp[cod_barra],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[cod_barra_tratado]),
			    USERELATIONSHIP(calendario[Date],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[dat_ult_venda])
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: d31cf0a2-8bf9-4210-bf6a-1a70fcd2d16e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure *vlr_total_lucro =
			CALCULATE(SUM(mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[vlr_total_lucro]),
			    USERELATIONSHIP(produto_gcp[cod_barra],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[cod_barra_tratado]),
			    USERELATIONSHIP(calendario[Date],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[dat_ult_venda])
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: c9b8bd01-ab6f-4a48-9ddc-8c40bcf6bfc3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure *qtd_total_vendida =
			CALCULATE(SUM(mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[qtd_total_vendida]),
			    USERELATIONSHIP(produto_gcp[cod_barra],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[cod_barra_tratado]),
			    USERELATIONSHIP(calendario[Date],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[dat_ult_venda])
			)
		formatString: #,0
		lineageTag: b734e2f6-286c-4032-9f13-1082d1ca60ee

	measure *qtd_total_estoque =
			CALCULATE(SUM(mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[qtd_total_estoque]),
			    USERELATIONSHIP(produto_gcp[cod_barra],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[cod_barra_tratado]),
			    USERELATIONSHIP(calendario[Date],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[dat_ult_venda])
			)
		formatString: #,0
		lineageTag: a26fb3f5-f14b-4374-80ac-abb0a756f87b

	measure *qtd_total_comprada =
			CALCULATE(SUM(mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[qtd_total_comprada]),
			    USERELATIONSHIP(produto_gcp[cod_barra],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[cod_barra_tratado]),
			    USERELATIONSHIP(calendario[Date],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[dat_ult_venda])
			)
		formatString: #,0
		lineageTag: 7b8b60d7-52a5-4d35-b005-298e6dc86815

	measure *vlr_total_comprado =
			CALCULATE(SUM(mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[vlr_total_comprado]),
			    USERELATIONSHIP(produto_gcp[cod_barra],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[cod_barra_tratado]),
			    USERELATIONSHIP(calendario[Date],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[dat_ult_venda])
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 42973786-4f2a-489d-ada1-8556b4fd0c01

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure *vlr_custo_estoque =
			CALCULATE(SUM(mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[vlr_custo_estoque]),
			    USERELATIONSHIP(produto_gcp[cod_barra],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[cod_barra_tratado]),
			    USERELATIONSHIP(calendario[Date],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[dat_ult_venda])
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: a9deab62-73c1-49ae-838f-d92fcd6482a9

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure *skus_prod_com_estoque =
			CALCULATE(DISTINCTCOUNT(mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[cod_barra]),
			    USERELATIONSHIP(produto_gcp[cod_barra],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[cod_barra_tratado]),
			    USERELATIONSHIP(calendario[Date],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[dat_ult_venda])
			)
		formatString: 0
		lineageTag: 873946d4-c300-4307-9d52-c1e81a3ff15d

	measure *qtd_dias_sem_vendas =
			CALCULATE(SUM(mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[qtd_dias_sem_vendas]),
			    USERELATIONSHIP(produto_gcp[cod_barra],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[cod_barra_tratado]),
			    USERELATIONSHIP(calendario[Date],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[dat_ult_venda])
			)
		formatString: #,0
		lineageTag: fc062da1-a90a-4718-8612-a279c2086871

	measure *faturamento_potencial =
			CALCULATE(SUM(mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[faturamento_potencial]),
			    USERELATIONSHIP(produto_gcp[cod_barra],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[cod_barra_tratado]),
			    USERELATIONSHIP(calendario[Date],mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[dat_ult_venda])
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 3353a238-c96a-4a55-80f9-9e6f8e722dd6

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column num_cnpj
		dataType: string
		lineageTag: 7f570739-6d23-41e4-b5e3-302dfb64b86c
		summarizeBy: none
		sourceColumn: num_cnpj

		annotation SummarizationSetBy = Automatic

	column cod_barra
		dataType: double
		lineageTag: 1f478f2f-eb30-433c-9941-24c014743fe0
		summarizeBy: sum
		sourceColumn: cod_barra

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dat_ult_atualiza_estoque
		dataType: dateTime
		formatString: Long Date
		lineageTag: 86d431f3-97e9-4687-bdaa-12a15e60a83e
		summarizeBy: none
		sourceColumn: dat_ult_atualiza_estoque

		variation Variation
			isDefault
			relationship: 98c90405-07be-4e2a-8668-c2787661d548
			defaultHierarchy: LocalDateTable_b43f05b7-57ac-45a5-991c-7e457ddc23b0.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column qtd_total_estoque
		dataType: double
		lineageTag: 17ffccb3-7a3a-4cf0-b0ef-a35be7084eab
		summarizeBy: sum
		sourceColumn: qtd_total_estoque

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vlr_custo_estoque
		dataType: double
		lineageTag: de354944-0e91-4c51-996e-86b580c67ef6
		summarizeBy: sum
		sourceColumn: vlr_custo_estoque

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dat_ult_venda
		dataType: dateTime
		formatString: Short Date
		lineageTag: 20ec4824-21d9-4b0b-be74-8d9ecd57b4f1
		summarizeBy: none
		sourceColumn: dat_ult_venda

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column qtd_dias_sem_vendas
		dataType: int64
		formatString: 0
		lineageTag: cf693fe3-3695-42a4-92d4-7c9f50f53572
		summarizeBy: sum
		sourceColumn: qtd_dias_sem_vendas

		annotation SummarizationSetBy = Automatic

	column qtd_total_vendida
		dataType: double
		lineageTag: 1bcd3d1b-34ff-446f-b763-927302567162
		summarizeBy: sum
		sourceColumn: qtd_total_vendida

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vlr_total_vendido
		dataType: double
		lineageTag: 0dd695f5-0f94-42d4-a78f-ca486894b101
		summarizeBy: sum
		sourceColumn: vlr_total_vendido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vlr_total_lucro
		dataType: double
		lineageTag: bdfc9e7b-1249-4f83-a766-ece9a5668317
		summarizeBy: sum
		sourceColumn: vlr_total_lucro

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dat_ult_compra
		dataType: dateTime
		formatString: Short Date
		lineageTag: 974afb24-ccc8-492e-b28a-eac640fba6d5
		summarizeBy: none
		sourceColumn: dat_ult_compra

		variation Variation
			isDefault
			relationship: b586dc5a-65e6-4f43-942e-df966b7111cb
			defaultHierarchy: LocalDateTable_c110d241-dabe-4390-8352-c1870dab0c41.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column qtd_total_comprada
		dataType: double
		lineageTag: d5b3b4a5-4cfb-497f-89c7-6112c4ed0644
		summarizeBy: sum
		sourceColumn: qtd_total_comprada

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vlr_total_comprado
		dataType: double
		lineageTag: 82f3f274-3e9d-4169-9a43-96dcd840934c
		summarizeBy: sum
		sourceColumn: vlr_total_comprado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column curva_abc
		dataType: string
		lineageTag: eca157d7-4144-4225-9ad5-cfa2deaeb396
		summarizeBy: none
		sourceColumn: curva_abc

		annotation SummarizationSetBy = Automatic

	column classificacao_estrela
		dataType: string
		lineageTag: 02866e6a-e08e-4ea2-95dc-feeb8c388bc2
		summarizeBy: none
		sourceColumn: classificacao_estrela

		annotation SummarizationSetBy = Automatic

	column diagnostico_estoque
		dataType: string
		lineageTag: 20cae324-9a78-47a1-a5c6-4d1e25c79965
		summarizeBy: none
		sourceColumn: diagnostico_estoque

		annotation SummarizationSetBy = Automatic

	column cod_barra_tratado =
			
			VAR padrao = LOOKUPVALUE(
			    produto_gcp[cod_barra],
			    produto_gcp[cod_barra],
			    mv_produtos_com_estoque_sem_vendas_mais_de_90_dias[cod_barra]
			)
			RETURN
			IF(
			    ISBLANK(padrao),
			    0,
			    padrao
			)
		formatString: 0
		lineageTag: a0116341-9d7a-4c9e-b579-49e7f9ab36f5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column icone_diagnostico_estoque =
			
			VAR Diagnostico = TRIM([diagnostico_estoque])
			RETURN
			SWITCH(
			    TRUE(),
			    Diagnostico = "OK", "✅"& Diagnostico,
			    Diagnostico = "Estoque encalhado", "📦"& Diagnostico,
			    Diagnostico = "Estoque crítico", "⚠️"& Diagnostico,
			    "❓"
			)
		lineageTag: b1ed961d-7101-4de9-9049-df2e6f3d3197
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column icone_curva_abc =
			
			VAR curva_abc = TRIM([curva_abc])
			RETURN
			SWITCH(
			    TRUE(),
			    curva_abc = "A", "🟢"& curva_abc,
			    curva_abc = "B", "🟡"& curva_abc,
			    curva_abc = "C", "🔴"& curva_abc
			)
		lineageTag: 705a4eb5-ed49-4803-a742-61bf6d60af95
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column faturamento_potencial
		dataType: double
		lineageTag: 4db45f52-02d3-49d8-b1a0-68f781e7988d
		summarizeBy: sum
		sourceColumn: faturamento_potencial

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition mv_produtos_com_estoque_sem_vendas_mais_de_90_dias = m
		mode: import
		source =
				let
				    NomeTabela = "mv_produtos_com_estoque_sem_vendas_mais_de_90_dias_" & Text.From(cliente),
				
				    Fonte = AmazonRedshift.Database("bc-prod.c9lkmnbigxth.us-east-1.redshift.amazonaws.com:5439","business_connect"),
				
				    associacao = Fonte{[Name="associacao"]}[Data],
				
				    Resultado = associacao{[Name=NomeTabela]}[Data],
				
				    #"Linhas Filtradas" = Table.SelectRows(
				        Resultado,
				        each true
				    ),
				
				    #"Columns removed by Measure Killer" = Table.SelectColumns(
				        #"Linhas Filtradas",
				        {
				            "faturamento_potencial",
				            "dat_ult_compra",
				            "curva_abc",
				            "diagnostico_estoque",
				            "dat_ult_venda",
				            "vlr_total_lucro",
				            "vlr_total_comprado",
				            "qtd_total_vendida",
				            "vlr_total_vendido",
				            "qtd_total_comprada",
				            "qtd_total_estoque",
				            "qtd_dias_sem_vendas",
				            "vlr_custo_estoque",
				            "classificacao_estrela",
				            "num_cnpj",
				            "dat_ult_atualiza_estoque",
				            "cod_barra"
				        }
				    )
				
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

